#!/usr/bin/env bash

#dont push log data to master
# Allows us to read user input below, assigns stdin to keyboard
exec < /dev/tty
STRING_PREFIX="[post-commit hook]"

echo "$STRING_PREFIX Cheking for bad strings"
BAD_STRING_LIST=('var_dump' 'alert(' 'alert (' 'console.log')

for BAD_STRING in $BAD_STRING_LIST[*]
    do
        VAR=$(git diff | grep -wi $BAD_STRING)
        if [[ ! -z "$VAR" ]]
            then
                echo "$STRING_PREFIX You've left a '$BAD_STRING' in one of your files! Aborting commit..."
                exit 1
        fi
done

if [[ -d "./includes" && -d "./modules" && -d "./misc" && -d "./themes" ]]
    then
        # Drupal site detected
        source .git/hooks/drupal-pre-commit
fi

#RESULT=$(git symbolic-ref HEAD 2>/dev/null) = "refs/heads/master"
echo "$STRING_PREFIX Cheking for master branch."
if [[ `git branch | grep \* | cut -f2 -d' '` == "master" ]]
    then
        while true
            do
                read -p "$STRING_PREFIX Looks like you're going to push to the master branch continue? [Y/n]" yn
                if [ "$yn" = "" ]
                    then
                        yn='Y'
                fi
                case $yn in
                    [Yy] ) echo "$STRING_PREFIX Pushing to  master."; break;;
                    [Nn] ) echo "$STRING_PREFIX Exiting commit."; exit 11;;
                    * ) echo "$STRING_PREFIX Please answer y or n for yes or no.";;
                esac
        done

        if [ $? -eq 11 ]; then  exit 1; fi  
fi

echo "$STRING_PREFIX Perfect validation!"
echo "$STRING_PREFIX Commit done!"
exit;
